import type { BoardProfile, HardwareConfig } from '../types/hardware'

export const ESP32_DEVKIT_V1_30P: BoardProfile = {
  id: 'esp32-devkit-v1-30p',
  name: 'ESP32 DevKit V1 (30-pin)',
  chip_family: 'ESP32-D0WDQ6',
  form_factor: 'devkit-v1-30p',
  pin_count: 30,
  left_header: [
    {
      pin_number: 1,
      label: 'EN',
      gpio: null,
      capabilities: ['reset'],
      is_strapping: false,
      notes: 'Chip enable / Reset line. Active LOW.',
    },
    {
      pin_number: 2,
      label: 'VP (GPIO36)',
      gpio: 36,
      capabilities: ['gpio_in', 'adc1'],
      is_strapping: false,
      notes: 'Input-only. No internal pull-up/pull-down resistor. ADC1 channel 0.',
    },
    {
      pin_number: 3,
      label: 'VN (GPIO39)',
      gpio: 39,
      capabilities: ['gpio_in', 'adc1'],
      is_strapping: false,
      notes: 'Input-only. No internal pull-up/pull-down resistor. ADC1 channel 3.',
    },
    {
      pin_number: 4,
      label: 'D34',
      gpio: 34,
      capabilities: ['gpio_in', 'adc1'],
      is_strapping: false,
      notes: 'Input-only pin. ADC1 channel 6.',
    },
    {
      pin_number: 5,
      label: 'D35',
      gpio: 35,
      capabilities: ['gpio_in', 'adc1'],
      is_strapping: false,
      notes: 'Input-only pin. ADC1 channel 7.',
    },
    {
      pin_number: 6,
      label: 'D32',
      gpio: 32,
      capabilities: ['gpio_in', 'gpio_out', 'adc1', 'touch'],
      is_strapping: false,
      notes: 'ADC1 channel 4, Touch 9, 32KHz RTC crystal.',
    },
    {
      pin_number: 7,
      label: 'D33',
      gpio: 33,
      capabilities: ['gpio_in', 'gpio_out', 'adc1', 'touch'],
      is_strapping: false,
      notes: 'ADC1 channel 5, Touch 8, 32KHz RTC crystal.',
    },
    {
      pin_number: 8,
      label: 'D25',
      gpio: 25,
      capabilities: ['gpio_in', 'gpio_out', 'dac', 'adc2'],
      is_strapping: false,
      notes: 'DAC Channel 1 (8-bit analog output). ADC2 channel 8.',
    },
    {
      pin_number: 9,
      label: 'D26',
      gpio: 26,
      capabilities: ['gpio_in', 'gpio_out', 'dac', 'adc2'],
      is_strapping: false,
      notes: 'DAC Channel 2 (8-bit analog output). ADC2 channel 9.',
    },
    {
      pin_number: 10,
      label: 'D27',
      gpio: 27,
      capabilities: ['gpio_in', 'gpio_out', 'adc2', 'touch'],
      is_strapping: false,
      notes: 'ADC2 channel 7, Touch 7.',
    },
    {
      pin_number: 11,
      label: 'D14',
      gpio: 14,
      capabilities: ['gpio_in', 'gpio_out', 'adc2', 'touch', 'spi_sck'],
      is_strapping: false,
      notes: 'HSPI SCK, ADC2 channel 6, Touch 6.',
    },
    {
      pin_number: 12,
      label: 'D12',
      gpio: 12,
      capabilities: ['gpio_in', 'gpio_out', 'adc2', 'touch', 'spi_miso'],
      is_strapping: true,
      notes: 'MTDI strapping pin. Controls internal flash voltage. Avoid pulling HIGH during boot.',
    },
    {
      pin_number: 13,
      label: 'D13',
      gpio: 13,
      capabilities: ['gpio_in', 'gpio_out', 'adc2', 'touch', 'spi_mosi'],
      is_strapping: false,
      notes: 'HSPI MOSI, ADC2 channel 4, Touch 4.',
    },
    {
      pin_number: 14,
      label: 'GND',
      gpio: null,
      capabilities: ['gnd'],
      is_strapping: false,
      notes: 'Common system ground.',
    },
    {
      pin_number: 15,
      label: 'VIN (5V)',
      gpio: null,
      capabilities: ['power_5v'],
      is_strapping: false,
      notes: '5V power input from USB or external regulator.',
    },
  ],
  right_header: [
    {
      pin_number: 16,
      label: 'D23 (MOSI)',
      gpio: 23,
      capabilities: ['gpio_in', 'gpio_out', 'spi_mosi'],
      is_strapping: false,
      notes: 'Default VSPI MOSI (Master Out Slave In).',
    },
    {
      pin_number: 17,
      label: 'D22 (SCL)',
      gpio: 22,
      capabilities: ['gpio_in', 'gpio_out', 'i2c_scl'],
      is_strapping: false,
      notes: 'Default hardware I2C SCL (Clock). Recommended for OLED.',
    },
    {
      pin_number: 18,
      label: 'TX0 (GPIO1)',
      gpio: 1,
      capabilities: ['gpio_in', 'gpio_out', 'uart_tx'],
      is_strapping: false,
      notes: 'UART0 TX (connected to onboard USB-UART chip).',
    },
    {
      pin_number: 19,
      label: 'RX0 (GPIO3)',
      gpio: 3,
      capabilities: ['gpio_in', 'gpio_out', 'uart_rx'],
      is_strapping: false,
      notes: 'UART0 RX (connected to onboard USB-UART chip).',
    },
    {
      pin_number: 20,
      label: 'D21 (SDA)',
      gpio: 21,
      capabilities: ['gpio_in', 'gpio_out', 'i2c_sda'],
      is_strapping: false,
      notes: 'Default hardware I2C SDA (Data). Recommended for OLED.',
    },
    {
      pin_number: 21,
      label: 'D19 (MISO)',
      gpio: 19,
      capabilities: ['gpio_in', 'gpio_out', 'spi_miso'],
      is_strapping: false,
      notes: 'Default VSPI MISO (Master In Slave Out).',
    },
    {
      pin_number: 22,
      label: 'D18 (SCK)',
      gpio: 18,
      capabilities: ['gpio_in', 'gpio_out', 'spi_sck'],
      is_strapping: false,
      notes: 'Default VSPI SCK (Clock).',
    },
    {
      pin_number: 23,
      label: 'D5 (CS)',
      gpio: 5,
      capabilities: ['gpio_in', 'gpio_out', 'spi_cs'],
      is_strapping: true,
      notes: 'VSPI CS (Chip Select). Strapping pin for timing config.',
    },
    {
      pin_number: 24,
      label: 'TX2 (GPIO17)',
      gpio: 17,
      capabilities: ['gpio_in', 'gpio_out', 'uart_tx'],
      is_strapping: false,
      notes: 'UART2 TX (Secondary serial).',
    },
    {
      pin_number: 25,
      label: 'RX2 (GPIO16)',
      gpio: 16,
      capabilities: ['gpio_in', 'gpio_out', 'uart_rx'],
      is_strapping: false,
      notes: 'UART2 RX (Secondary serial).',
    },
    {
      pin_number: 26,
      label: 'D4',
      gpio: 4,
      capabilities: ['gpio_in', 'gpio_out', 'adc2', 'touch'],
      is_strapping: false,
      notes: 'ADC2 channel 0, Touch 0.',
    },
    {
      pin_number: 27,
      label: 'D2 (LED)',
      gpio: 2,
      capabilities: ['gpio_in', 'gpio_out', 'adc2', 'touch'],
      is_strapping: true,
      notes: 'Onboard LED on most DevKits. Strapping pin: must be LOW or floating for flashing.',
    },
    {
      pin_number: 28,
      label: 'D15',
      gpio: 15,
      capabilities: ['gpio_in', 'gpio_out', 'adc2', 'touch'],
      is_strapping: true,
      notes: 'MTDO strapping pin (boot debug log output).',
    },
    {
      pin_number: 29,
      label: 'GND',
      gpio: null,
      capabilities: ['gnd'],
      is_strapping: false,
      notes: 'Common system ground.',
    },
    {
      pin_number: 30,
      label: '3V3',
      gpio: null,
      capabilities: ['power_3v3'],
      is_strapping: false,
      notes: '3.3V regulated power rail (up to 500-600mA).',
    },
  ],
}

export const ESP32_DEVKIT_V1_38P: BoardProfile = {
  id: 'esp32-devkit-v1-38p',
  name: 'ESP32 DevKit V1 (38-pin)',
  chip_family: 'ESP32-D0WDQ6',
  form_factor: 'devkit-v1-38p',
  pin_count: 38,
  left_header: [
    {
      pin_number: 1,
      label: '3V3',
      gpio: null,
      capabilities: ['power_3v3'],
      is_strapping: false,
      notes: '3.3V power supply rail.',
    },
    {
      pin_number: 2,
      label: 'EN',
      gpio: null,
      capabilities: ['reset'],
      is_strapping: false,
      notes: 'Chip enable / Reset button (active LOW).',
    },
    {
      pin_number: 3,
      label: 'VP (GPIO36)',
      gpio: 36,
      capabilities: ['gpio_in', 'adc1'],
      is_strapping: false,
      notes: 'Sensor VP. Input-only, ADC1 channel 0, low noise.',
    },
    {
      pin_number: 4,
      label: 'VN (GPIO39)',
      gpio: 39,
      capabilities: ['gpio_in', 'adc1'],
      is_strapping: false,
      notes: 'Sensor VN. Input-only, ADC1 channel 3, low noise.',
    },
    {
      pin_number: 5,
      label: 'P34',
      gpio: 34,
      capabilities: ['gpio_in', 'adc1'],
      is_strapping: false,
      notes: 'Input-only pin. ADC1 channel 6.',
    },
    {
      pin_number: 6,
      label: 'P35',
      gpio: 35,
      capabilities: ['gpio_in', 'adc1'],
      is_strapping: false,
      notes: 'Input-only pin. ADC1 channel 7.',
    },
    {
      pin_number: 7,
      label: 'P32',
      gpio: 32,
      capabilities: ['gpio_in', 'gpio_out', 'adc1', 'touch'],
      is_strapping: false,
      notes: 'ADC1 channel 4, Touch 9, 32KHz RTC crystal.',
    },
    {
      pin_number: 8,
      label: 'P33',
      gpio: 33,
      capabilities: ['gpio_in', 'gpio_out', 'adc1', 'touch'],
      is_strapping: false,
      notes: 'ADC1 channel 5, Touch 8, 32KHz RTC crystal.',
    },
    {
      pin_number: 9,
      label: 'P25',
      gpio: 25,
      capabilities: ['gpio_in', 'gpio_out', 'dac', 'adc2'],
      is_strapping: false,
      notes: 'DAC Channel 1 (8-bit analog output). ADC2 channel 8.',
    },
    {
      pin_number: 10,
      label: 'P26',
      gpio: 26,
      capabilities: ['gpio_in', 'gpio_out', 'dac', 'adc2'],
      is_strapping: false,
      notes: 'DAC Channel 2 (8-bit analog output). ADC2 channel 9.',
    },
    {
      pin_number: 11,
      label: 'P27',
      gpio: 27,
      capabilities: ['gpio_in', 'gpio_out', 'adc2', 'touch'],
      is_strapping: false,
      notes: 'ADC2 channel 7, Touch 7.',
    },
    {
      pin_number: 12,
      label: 'P14',
      gpio: 14,
      capabilities: ['gpio_in', 'gpio_out', 'adc2', 'touch', 'spi_sck'],
      is_strapping: false,
      notes: 'HSPI SCK, ADC2 channel 6, Touch 6.',
    },
    {
      pin_number: 13,
      label: 'P12',
      gpio: 12,
      capabilities: ['gpio_in', 'gpio_out', 'adc2', 'touch', 'spi_miso'],
      is_strapping: true,
      notes: 'MTDI strapping pin. Controls flash voltage (3.3V vs 1.8V). Do not pull HIGH during boot.',
    },
    {
      pin_number: 14,
      label: 'GND',
      gpio: null,
      capabilities: ['gnd'],
      is_strapping: false,
      notes: 'Common Ground reference.',
    },
    {
      pin_number: 15,
      label: 'P13',
      gpio: 13,
      capabilities: ['gpio_in', 'gpio_out', 'adc2', 'touch', 'spi_mosi'],
      is_strapping: false,
      notes: 'HSPI MOSI, ADC2 channel 4, Touch 4.',
    },
    {
      pin_number: 16,
      label: 'SD2',
      gpio: 9,
      capabilities: ['gpio_in', 'gpio_out', 'flash_reserved'],
      is_strapping: false,
      notes: 'GPIO 9 (D2). Connected to internal SPI flash memory! Avoid using.',
    },
    {
      pin_number: 17,
      label: 'SD3',
      gpio: 10,
      capabilities: ['gpio_in', 'gpio_out', 'flash_reserved'],
      is_strapping: false,
      notes: 'GPIO 10 (D3). Connected to internal SPI flash memory! Avoid using.',
    },
    {
      pin_number: 18,
      label: 'CMD',
      gpio: 11,
      capabilities: ['gpio_in', 'gpio_out', 'flash_reserved'],
      is_strapping: false,
      notes: 'GPIO 11 (CMD). Connected to internal SPI flash memory! Avoid using.',
    },
    {
      pin_number: 19,
      label: '5V',
      gpio: null,
      capabilities: ['power_5v'],
      is_strapping: false,
      notes: '5V power input from USB or external regulator.',
    },
  ],
  right_header: [
    {
      pin_number: 20,
      label: 'GND',
      gpio: null,
      capabilities: ['gnd'],
      is_strapping: false,
      notes: 'Common Ground reference.',
    },
    {
      pin_number: 21,
      label: 'P23',
      gpio: 23,
      capabilities: ['gpio_in', 'gpio_out', 'spi_mosi'],
      is_strapping: false,
      notes: 'Default VSPI MOSI (Master Out Slave In).',
    },
    {
      pin_number: 22,
      label: 'P22 (SCL)',
      gpio: 22,
      capabilities: ['gpio_in', 'gpio_out', 'i2c_scl'],
      is_strapping: false,
      notes: 'Default hardware I2C SCL (Clock). Recommended for OLED SCL.',
    },
    {
      pin_number: 23,
      label: 'TX',
      gpio: 1,
      capabilities: ['gpio_in', 'gpio_out', 'uart_tx'],
      is_strapping: false,
      notes: 'UART0 TX (connected to USB-UART chip for flashing and logging).',
    },
    {
      pin_number: 24,
      label: 'RX',
      gpio: 3,
      capabilities: ['gpio_in', 'gpio_out', 'uart_rx'],
      is_strapping: false,
      notes: 'UART0 RX (connected to USB-UART chip for flashing and logging).',
    },
    {
      pin_number: 25,
      label: 'P21 (SDA)',
      gpio: 21,
      capabilities: ['gpio_in', 'gpio_out', 'i2c_sda'],
      is_strapping: false,
      notes: 'Default hardware I2C SDA (Data). Recommended for OLED SDA.',
    },
    {
      pin_number: 26,
      label: 'GND',
      gpio: null,
      capabilities: ['gnd'],
      is_strapping: false,
      notes: 'Common Ground reference.',
    },
    {
      pin_number: 27,
      label: 'P19',
      gpio: 19,
      capabilities: ['gpio_in', 'gpio_out', 'spi_miso'],
      is_strapping: false,
      notes: 'Default VSPI MISO (Master In Slave Out).',
    },
    {
      pin_number: 28,
      label: 'P18',
      gpio: 18,
      capabilities: ['gpio_in', 'gpio_out', 'spi_sck'],
      is_strapping: false,
      notes: 'Default VSPI SCK (Clock).',
    },
    {
      pin_number: 29,
      label: 'P5',
      gpio: 5,
      capabilities: ['gpio_in', 'gpio_out', 'spi_cs'],
      is_strapping: true,
      notes: 'VSPI CS (Chip Select). Strapping pin (timing configuration).',
    },
    {
      pin_number: 30,
      label: 'P17',
      gpio: 17,
      capabilities: ['gpio_in', 'gpio_out', 'uart_tx'],
      is_strapping: false,
      notes: 'UART2 TX (Secondary UART port).',
    },
    {
      pin_number: 31,
      label: 'P16',
      gpio: 16,
      capabilities: ['gpio_in', 'gpio_out', 'uart_rx'],
      is_strapping: false,
      notes: 'UART2 RX (Secondary UART port).',
    },
    {
      pin_number: 32,
      label: 'P4',
      gpio: 4,
      capabilities: ['gpio_in', 'gpio_out', 'adc2', 'touch'],
      is_strapping: false,
      notes: 'ADC2 channel 0, Touch 0.',
    },
    {
      pin_number: 33,
      label: 'P0 (BOOT)',
      gpio: 0,
      capabilities: ['gpio_in', 'gpio_out', 'adc2', 'touch'],
      is_strapping: true,
      notes: 'Boot button. Strapping pin: LOW puts chip in UART download bootloader mode.',
    },
    {
      pin_number: 34,
      label: 'P2 (LED)',
      gpio: 2,
      capabilities: ['gpio_in', 'gpio_out', 'adc2', 'touch'],
      is_strapping: true,
      notes: 'On-board LED on many DevKits. Strapping pin (must be floating or LOW for flashing).',
    },
    {
      pin_number: 35,
      label: 'P15',
      gpio: 15,
      capabilities: ['gpio_in', 'gpio_out', 'adc2', 'touch'],
      is_strapping: true,
      notes: 'MTDO strapping pin (enables debug print if HIGH at boot).',
    },
    {
      pin_number: 36,
      label: 'SD1',
      gpio: 8,
      capabilities: ['gpio_in', 'gpio_out', 'flash_reserved'],
      is_strapping: false,
      notes: 'GPIO 8 (D1). Connected to internal SPI flash memory! Avoid using.',
    },
    {
      pin_number: 37,
      label: 'SD0',
      gpio: 7,
      capabilities: ['gpio_in', 'gpio_out', 'flash_reserved'],
      is_strapping: false,
      notes: 'GPIO 7 (D0). Connected to internal SPI flash memory! Avoid using.',
    },
    {
      pin_number: 38,
      label: 'CLK',
      gpio: 6,
      capabilities: ['gpio_in', 'gpio_out', 'flash_reserved'],
      is_strapping: false,
      notes: 'GPIO 6 (CLK). Connected to internal SPI flash memory! Avoid using.',
    },
  ],
}

export const STANDARD_BOARD_PROFILES: BoardProfile[] = [
  ESP32_DEVKIT_V1_38P,
  ESP32_DEVKIT_V1_30P,
]

export const DEFAULT_HARDWARE_CONFIG: HardwareConfig = {
  version: 1,
  board_id: 'esp32-devkit-v1-38p',
  board_name: 'ESP32 DevKit V1 (38-pin)',
  peripherals: [
    {
      id: 'oled-display-primary',
      type: 'OLED_128X64_I2C',
      name: '1.3" Monochrome OLED (128x64)',
      controller: 'SH1106',
      i2c_address: '0x3C',
      pins: {
        VCC: '3V3',
        GND: 'GND',
        SDA: 'D21 (SDA)',
        SCL: 'D22 (SCL)',
      },
      status: 'configured',
    },
  ],
}
