/**
 * Spec 006 — Video Reel Exporter & Code Generator
 * Generates C/C++ PROGMEM headers for Arduino / PlatformIO, raw binary reels (.bin),
 * and triggers local browser file downloads.
 */

import type { VideoReel } from '../types/video'
import { DisplayProfileFactory } from '../factories/DisplayProfileFactory'
import { ExporterFactory } from '../factories/ExporterFactory'

/**
 * Generates a single fully self-contained Arduino .ino file containing the
 * complete PixelForge ESP32 firmware. All source files (config, crc8, protocol,
 * display, main) are merged in dependency order into one Arduino-IDE-compatible sketch.
 *
 * Required Arduino Libraries (install via Library Manager):
 *   - U8g2 by Oliver (olikraus)
 *   - ArduinoJson by Benoit Blanchon
 *
 * After flashing this sketch the ESP32 will accept PixelForge serial commands
 * including CMD_START_REEL_UPLOAD (0x07) and CMD_PLAY_REEL (0x09), enabling
 * the "Upload & Play on OLED" button in the Video Converter.
 */
export function generateFirmwareSketch(): string {
  return `// ============================================================================
// PixelForge ESP32 Firmware — Single-File Arduino Sketch
// Generated by PixelForge Desktop App
//
// ⚡ Flash this to your ESP32 to enable "Upload & Play on OLED" in PixelForge.
//
// Required Libraries (Install via Arduino Library Manager):
//   1. U8g2  by Oliver  (olikraus/U8g2)
//   2. ArduinoJson  by Benoit Blanchon
//
// Hardware Wiring:
//   OLED VCC → ESP32 3.3V
//   OLED GND → ESP32 GND
//   OLED SCL → GPIO 22
//   OLED SDA → GPIO 21
//   OLED I2C Address: 0x3C
//
// Board Settings (Arduino IDE):
//   Board: "ESP32 Dev Module"
//   Upload Speed: 921600
//   CPU Frequency: 240MHz
// ============================================================================

#include <Arduino.h>
#include <Wire.h>
#include <U8g2lib.h>
#include <ArduinoJson.h>
#include <LittleFS.h>

// ============================================================================
// Configuration
// ============================================================================
#define OLED_SDA 21
#define OLED_SCL 22
#define OLED_I2C_ADDR 0x3C
#define SERIAL_BAUD_RATE 115200
#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 64
#define DISPLAY_COLOR_DEPTH 1
#define CANONICAL_FRAME_SIZE 1024  // 128 * 64 / 8

// Controller: comment/uncomment to match your OLED hardware
#define OLED_CONTROLLER_SH1106
// #define OLED_CONTROLLER_SSD1306

#if defined(OLED_CONTROLLER_SSD1306)
  #define DISPLAY_CONTROLLER_NAME "SSD1306"
#else
  #define DISPLAY_CONTROLLER_NAME "SH1106"
#endif

#define PROTOCOL_VERSION 1
#define FIRMWARE_VERSION "0.1.0"
#define DEVICE_NAME "PixelForge-ESP32"

// ============================================================================
// Protocol Constants
// ============================================================================
#define PROTOCOL_SOF 0xAA
#define PROTOCOL_EOF 0x55

// Host → Device commands
#define CMD_PING              0x01
#define CMD_GET_DEVICE_INFO   0x02
#define CMD_SEND_FRAME        0x03
#define CMD_CLEAR_DISPLAY     0x04
#define CMD_GET_TELEMETRY     0x05
#define CMD_RESTART_DEVICE    0x06
#define CMD_START_REEL_UPLOAD 0x07
#define CMD_APPEND_REEL_FRAME 0x08
#define CMD_PLAY_REEL         0x09
#define CMD_STOP_REEL         0x0A

// Device → Host responses
#define RESP_PONG             0x81
#define RESP_DEVICE_INFO      0x82
#define RESP_FRAME_ACK        0x83
#define RESP_CLEAR_ACK        0x84
#define RESP_TELEMETRY_DATA   0x85
#define RESP_RESTART_ACK      0x86
#define RESP_REEL_UPLOAD_ACK  0x87
#define RESP_REEL_FRAME_ACK   0x88
#define RESP_PLAY_REEL_ACK    0x89
#define RESP_STOP_REEL_ACK    0x8A
#define RESP_ERROR            0xFF

// ============================================================================
// CRC-8 (SMBus / ATM / ITU-T, Poly 0x07)
// ============================================================================
static uint8_t crc8_compute(const uint8_t* data, size_t len) {
    uint8_t crc = 0x00;
    for (size_t i = 0; i < len; i++) {
        crc ^= data[i];
        for (uint8_t b = 0; b < 8; b++) {
            crc = (crc & 0x80) ? ((crc << 1) ^ 0x07) : (crc << 1);
        }
    }
    return crc;
}

// ============================================================================
// Packet Structure
// ============================================================================
struct RxPacket {
    uint8_t  msgType;
    uint8_t  version;
    uint16_t length;
    uint8_t  payload[CANONICAL_FRAME_SIZE + 64];
};

// ============================================================================
// Protocol Handler (state-machine serial framer)
// ============================================================================
enum ParserState { WAIT_SOF, READ_HEADER, READ_PAYLOAD, READ_CRC, READ_EOF };

class ProtocolHandler {
public:
    ProtocolHandler() { reset(); }

    void reset() {
        state = WAIT_SOF;
        bytesRead = 0;
        packetReady = false;
        currentPacket.length = 0;
    }

    bool hasPacket() const { return packetReady; }
    const RxPacket& getPacket() const { return currentPacket; }
    void consumePacket() { packetReady = false; reset(); }

    void update() {
        if (packetReady) return;
        while (Serial.available() > 0) {
            uint8_t b = Serial.read();
            switch (state) {
                case WAIT_SOF:
                    if (b == PROTOCOL_SOF) { state = READ_HEADER; bytesRead = 0; }
                    break;
                case READ_HEADER:
                    headerBuf[bytesRead++] = b;
                    if (bytesRead == 4) {
                        currentPacket.msgType = headerBuf[0];
                        currentPacket.version = headerBuf[1];
                        currentPacket.length  = ((uint16_t)headerBuf[2] << 8) | headerBuf[3];
                        if (currentPacket.version != PROTOCOL_VERSION ||
                            currentPacket.length > sizeof(currentPacket.payload)) {
                            reset(); break;
                        }
                        state = (currentPacket.length == 0) ? READ_CRC : READ_PAYLOAD;
                        bytesRead = 0;
                    }
                    break;
                case READ_PAYLOAD:
                    currentPacket.payload[bytesRead++] = b;
                    if (bytesRead == currentPacket.length) state = READ_CRC;
                    break;
                case READ_CRC: {
                    // CRC covers: [msgType, version, lenH, lenL, payload...]
                    uint8_t crcData[4 + CANONICAL_FRAME_SIZE + 64];
                    memcpy(crcData, headerBuf, 4);
                    memcpy(crcData + 4, currentPacket.payload, currentPacket.length);
                    uint8_t expected = crc8_compute(crcData, 4 + currentPacket.length);
                    if (b != expected) { reset(); break; }
                    state = READ_EOF;
                    break;
                }
                case READ_EOF:
                    if (b == PROTOCOL_EOF) { packetReady = true; return; }
                    else { reset(); }
                    break;
            }
        }
    }

    void sendPacket(uint8_t msgType, const uint8_t* payload, uint16_t length) {
        uint8_t header[5] = {
            PROTOCOL_SOF, msgType, PROTOCOL_VERSION,
            (uint8_t)((length >> 8) & 0xFF), (uint8_t)(length & 0xFF)
        };
        // CRC over [msgType, version, lenH, lenL, payload]
        uint8_t crcData[4 + CANONICAL_FRAME_SIZE + 64];
        memcpy(crcData, &header[1], 4);
        if (payload && length > 0) memcpy(crcData + 4, payload, length);
        uint8_t crc = crc8_compute(crcData, 4 + length);

        Serial.write(header, 5);
        if (payload && length > 0) Serial.write(payload, length);
        Serial.write(crc);
        Serial.write((uint8_t)PROTOCOL_EOF);
        Serial.flush();
    }

    void sendPong()                          { uint8_t s=0; sendPacket(RESP_PONG, &s, 1); }
    void sendFrameAck(uint8_t s)             { sendPacket(RESP_FRAME_ACK, &s, 1); }
    void sendClearAck(uint8_t s)             { sendPacket(RESP_CLEAR_ACK, &s, 1); }
    void sendRestartAck(uint8_t s)           { sendPacket(RESP_RESTART_ACK, &s, 1); }

    void sendDeviceInfo(const char* json) {
        sendPacket(RESP_DEVICE_INFO, (const uint8_t*)json, strlen(json));
    }

    void sendError(uint8_t code, const char* msg) {
        uint8_t buf[128]; buf[0] = code;
        size_t n = min(strlen(msg), (size_t)120);
        memcpy(&buf[1], msg, n);
        sendPacket(RESP_ERROR, buf, 1 + n);
    }

    void sendTelemetry(uint32_t freeH, uint32_t minH, uint32_t totalH,
                       uint32_t uptime, uint16_t fpsX10, uint8_t contrast,
                       uint8_t wifi, uint32_t frames) {
        uint8_t p[24];
        p[0]=(freeH>>24)&0xFF;  p[1]=(freeH>>16)&0xFF;  p[2]=(freeH>>8)&0xFF;  p[3]=freeH&0xFF;
        p[4]=(minH>>24)&0xFF;   p[5]=(minH>>16)&0xFF;   p[6]=(minH>>8)&0xFF;   p[7]=minH&0xFF;
        p[8]=(totalH>>24)&0xFF; p[9]=(totalH>>16)&0xFF; p[10]=(totalH>>8)&0xFF; p[11]=totalH&0xFF;
        p[12]=(uptime>>24)&0xFF; p[13]=(uptime>>16)&0xFF; p[14]=(uptime>>8)&0xFF; p[15]=uptime&0xFF;
        p[16]=(fpsX10>>8)&0xFF; p[17]=fpsX10&0xFF;
        p[18]=contrast; p[19]=wifi;
        p[20]=(frames>>24)&0xFF; p[21]=(frames>>16)&0xFF; p[22]=(frames>>8)&0xFF; p[23]=frames&0xFF;
        sendPacket(RESP_TELEMETRY_DATA, p, 24);
    }

private:
    ParserState state;
    uint8_t  headerBuf[4];
    uint16_t bytesRead;
    uint8_t  expectedCrc;
    bool     packetReady;
    RxPacket currentPacket;
};

// ============================================================================
// Display Driver
// ============================================================================
class DisplayDriver {
public:
#if defined(OLED_CONTROLLER_SSD1306)
    DisplayDriver() : u8g2(U8G2_R0, U8X8_PIN_NONE, OLED_SCL, OLED_SDA) {}
#else
    DisplayDriver() : u8g2(U8G2_R0, U8X8_PIN_NONE, OLED_SCL, OLED_SDA) {}
#endif

    bool init() {
        Wire.begin(OLED_SDA, OLED_SCL);
        u8g2.setI2CAddress(OLED_I2C_ADDR << 1);
        bool ok = u8g2.begin();
        u8g2.clearBuffer(); u8g2.sendBuffer();
        return ok;
    }

    void clear() { u8g2.clearBuffer(); u8g2.sendBuffer(); }

    void renderCanonicalFrame(const uint8_t* frame) {
        u8g2.clearBuffer();
        for (uint16_t y = 0; y < DISPLAY_HEIGHT; y++) {
            uint16_t rowOff = y * 16;
            for (uint16_t xb = 0; xb < 16; xb++) {
                uint8_t b = frame[rowOff + xb];
                if (!b) continue;
                uint16_t bx = xb * 8;
                for (uint8_t bit = 0; bit < 8; bit++) {
                    if (b & (0x80 >> bit)) u8g2.drawPixel(bx + bit, y);
                }
            }
        }
        u8g2.sendBuffer();
    }

private:
#if defined(OLED_CONTROLLER_SSD1306)
    U8G2_SSD1306_128X64_NONAME_F_HW_I2C u8g2;
#else
    U8G2_SH1106_128X64_NONAME_F_HW_I2C u8g2;
#endif
};

// ============================================================================
// Global state
// ============================================================================
ProtocolHandler protocol;
DisplayDriver   display;

static uint32_t totalFramesRendered = 0;
static uint32_t lastFrameRenderTime = 0;
static float    smoothedFps = 0.0f;

// Autonomous Reel Animation Engine
#define MAX_RAM_FRAMES 120
#define MAX_FLASH_REEL_FRAMES 1500
static uint8_t*  reelFrames[MAX_RAM_FRAMES] = {nullptr};
static uint8_t   streamFrameBuf[CANONICAL_FRAME_SIZE];
static uint16_t  reelFrameCount   = 0;
static uint16_t  reelTargetFps    = 15;
static uint32_t  reelIntervalMs   = 66;
static bool      isPlayingReel    = false;
static uint16_t  reelFrameIdx     = 0;
static uint32_t  lastReelTime     = 0;

static File      activeReelWriteFile;
static File      activeReelReadFile;
static bool      littleFsReady    = false;

void freeReelMemory() {
    for (int i = 0; i < MAX_RAM_FRAMES; i++) {
        if (reelFrames[i]) { free(reelFrames[i]); reelFrames[i] = nullptr; }
    }
}

void openReelReadStream() {
    if (activeReelReadFile) activeReelReadFile.close();
    if (littleFsReady && LittleFS.exists("/reel.pfr")) {
        activeReelReadFile = LittleFS.open("/reel.pfr", "r");
    }
}

bool loadReelFromFlash() {
    if (!littleFsReady || !LittleFS.exists("/reel.pfr")) return false;
    File f = LittleFS.open("/reel.pfr", "r");
    if (!f || f.size() < 8) { if (f) f.close(); return false; }

    uint8_t hdr[8];
    if (f.read(hdr, 8) != 8) { f.close(); return false; }
    if (hdr[0] != 'P' || hdr[1] != 'F' || hdr[2] != 'R' || hdr[3] != '1') { f.close(); return false; }

    uint16_t savedCount = ((uint16_t)hdr[4] << 8) | hdr[5];
    uint16_t savedFps   = ((uint16_t)hdr[6] << 8) | hdr[7];

    freeReelMemory();
    reelFrameCount = min((int)savedCount, MAX_FLASH_REEL_FRAMES);
    reelTargetFps  = savedFps > 0 ? savedFps : 15;
    reelIntervalMs = 1000 / reelTargetFps;

    uint16_t ramFrames = min((int)reelFrameCount, MAX_RAM_FRAMES);
    for (int i = 0; i < (int)ramFrames; i++) {
        reelFrames[i] = (uint8_t*)malloc(CANONICAL_FRAME_SIZE);
        if (reelFrames[i]) {
            f.read(reelFrames[i], CANONICAL_FRAME_SIZE);
        } else {
            break;
        }
    }
    f.close();

    if (reelFrameCount > 0) {
        openReelReadStream();
        isPlayingReel = true;
        reelFrameIdx = 0;
        lastReelTime = millis();
        return true;
    }
    return false;
}

// ============================================================================
// Command Dispatcher
// ============================================================================
void handleCommand(const RxPacket& p) {
    switch (p.msgType) {

        case CMD_PING:
            protocol.sendPong();
            break;

        case CMD_GET_DEVICE_INFO: {
            JsonDocument doc;
            doc["protocol_version"] = PROTOCOL_VERSION;
            doc["firmware_version"] = FIRMWARE_VERSION;
            doc["device_name"]      = DEVICE_NAME;
            doc["display_width"]    = DISPLAY_WIDTH;
            doc["display_height"]   = DISPLAY_HEIGHT;
            doc["color_depth"]      = DISPLAY_COLOR_DEPTH;
            doc["display_controller"] = DISPLAY_CONTROLLER_NAME;
            doc["flash_storage"]    = littleFsReady ? "LittleFS" : "None";
            char buf[256]; serializeJson(doc, buf);
            protocol.sendDeviceInfo(buf);
            break;
        }

        case CMD_CLEAR_DISPLAY:
            if (activeReelWriteFile) { activeReelWriteFile.flush(); activeReelWriteFile.close(); }
            isPlayingReel = false;
            display.clear();
            protocol.sendClearAck(0x00);
            break;

        case CMD_SEND_FRAME:
            if (p.length != CANONICAL_FRAME_SIZE) {
                protocol.sendFrameAck(0x01);
            } else {
                isPlayingReel = false;
                display.renderCanonicalFrame(p.payload);
                protocol.sendFrameAck(0x00);
                totalFramesRendered++;
                uint32_t now = millis();
                if (lastFrameRenderTime > 0 && now > lastFrameRenderTime) {
                    float inst = 1000.0f / (float)(now - lastFrameRenderTime);
                    smoothedFps = smoothedFps * 0.7f + inst * 0.3f;
                }
                lastFrameRenderTime = now;
            }
            break;

        case CMD_GET_TELEMETRY:
            protocol.sendTelemetry(
                ESP.getFreeHeap(), ESP.getMinFreeHeap(), ESP.getHeapSize(),
                millis() / 1000,
                (uint16_t)(smoothedFps * 10.0f),
                255, 0, totalFramesRendered
            );
            break;

        case CMD_RESTART_DEVICE:
            protocol.sendRestartAck(0x00);
            delay(50);
            ESP.restart();
            break;

        // ── Autonomous Reel Upload (persists into LittleFS Flash) ───────────
        case CMD_START_REEL_UPLOAD: {
            if (p.length < 4) { protocol.sendError(0x02, "Invalid reel start payload"); break; }
            isPlayingReel = false;
            freeReelMemory();

            uint16_t reqCount = ((uint16_t)p.payload[0] << 8) | p.payload[1];
            uint16_t reqFps   = ((uint16_t)p.payload[2] << 8) | p.payload[3];
            reelFrameCount  = min((int)reqCount, MAX_FLASH_REEL_FRAMES);
            reelTargetFps   = reqFps > 0 ? reqFps : 15;
            reelIntervalMs  = 1000 / reelTargetFps;

            uint16_t ramFrames = min((int)reelFrameCount, MAX_RAM_FRAMES);
            for (int i = 0; i < (int)ramFrames; i++) {
                reelFrames[i] = (uint8_t*)malloc(CANONICAL_FRAME_SIZE);
                if (!reelFrames[i]) break;
            }
            reelFrameIdx = 0;

            if (littleFsReady) {
                if (activeReelWriteFile) activeReelWriteFile.close();
                if (activeReelReadFile) activeReelReadFile.close();
                activeReelWriteFile = LittleFS.open("/reel.pfr", "w");
                if (activeReelWriteFile) {
                    uint8_t hdr[8] = {
                        'P', 'F', 'R', '1',
                        (uint8_t)(reelFrameCount >> 8), (uint8_t)(reelFrameCount & 0xFF),
                        (uint8_t)(reelTargetFps >> 8),  (uint8_t)(reelTargetFps & 0xFF)
                    };
                    activeReelWriteFile.write(hdr, 8);
                }
            }

            if (reelFrameCount > 0) protocol.sendPacket(RESP_REEL_UPLOAD_ACK, nullptr, 0);
            else protocol.sendError(0x05, "Insufficient memory for reel");
            break;
        }

        case CMD_APPEND_REEL_FRAME: {
            if (p.length < 2 + CANONICAL_FRAME_SIZE) {
                protocol.sendError(0x04, "Invalid reel frame payload length"); break;
            }
            uint16_t fi = ((uint16_t)p.payload[0] << 8) | p.payload[1];
            if (fi < reelFrameCount) {
                if (fi < MAX_RAM_FRAMES && reelFrames[fi]) {
                    memcpy(reelFrames[fi], &p.payload[2], CANONICAL_FRAME_SIZE);
                }
                if (activeReelWriteFile) {
                    activeReelWriteFile.write(&p.payload[2], CANONICAL_FRAME_SIZE);
                }
                protocol.sendPacket(RESP_REEL_FRAME_ACK, nullptr, 0);
            } else {
                protocol.sendPacket(RESP_REEL_FRAME_ACK, nullptr, 0);
            }
            break;
        }

        case CMD_PLAY_REEL: {
            if (activeReelWriteFile) { activeReelWriteFile.flush(); activeReelWriteFile.close(); }
            openReelReadStream();
            if (p.length >= 2) {
                uint16_t fps = ((uint16_t)p.payload[0] << 8) | p.payload[1];
                if (fps > 0) { reelTargetFps = fps; reelIntervalMs = 1000 / fps; }
            }
            isPlayingReel = true;
            reelFrameIdx  = 0;
            lastReelTime  = millis();
            protocol.sendPacket(RESP_PLAY_REEL_ACK, nullptr, 0);
            break;
        }

        case CMD_STOP_REEL:
            if (activeReelWriteFile) { activeReelWriteFile.flush(); activeReelWriteFile.close(); }
            if (activeReelReadFile) { activeReelReadFile.close(); }
            isPlayingReel = false;
            protocol.sendPacket(RESP_STOP_REEL_ACK, nullptr, 0);
            break;

        default:
            protocol.sendError(0x01, "Unsupported command");
            break;
    }
}

// ============================================================================
// Arduino Entry Points
// ============================================================================
void setup() {
    Serial.begin(SERIAL_BAUD_RATE);
    delay(50);
    display.init();
    display.clear();

    // Mount LittleFS partition and auto-play any previously saved reel
    littleFsReady = LittleFS.begin(true);
    if (littleFsReady) {
        loadReelFromFlash();
    }
}

void loop() {
    protocol.update();
    if (protocol.hasPacket()) {
        handleCommand(protocol.getPacket());
        protocol.consumePacket();
    }

    // Autonomous reel playback engine (runs independently across power cycles)
    if (isPlayingReel && reelFrameCount > 0) {
        uint32_t now = millis();
        if (now - lastReelTime >= reelIntervalMs) {
            lastReelTime = now;
            if (reelFrameIdx < MAX_RAM_FRAMES && reelFrames[reelFrameIdx]) {
                display.renderCanonicalFrame(reelFrames[reelFrameIdx]);
                totalFramesRendered++;
            } else if (activeReelReadFile) {
                uint32_t offset = 8 + (uint32_t)reelFrameIdx * CANONICAL_FRAME_SIZE;
                if (activeReelReadFile.seek(offset)) {
                    activeReelReadFile.read(streamFrameBuf, CANONICAL_FRAME_SIZE);
                    display.renderCanonicalFrame(streamFrameBuf);
                    totalFramesRendered++;
                }
            }
            reelFrameIdx = (reelFrameIdx + 1) % reelFrameCount;
        }
    }
}
`
}

/**
 * Triggers a browser download of the complete firmware as a single .ino file.
 */
export function downloadFirmwareSketch(): void {
  const code = generateFirmwareSketch()
  const blob = new Blob([code], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'PixelForge_Firmware.ino'
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}


/**
 * Generates a clean, copy-paste ready C/C++ header (.h) with PROGMEM storage.
 * Delegates to ExporterFactory (Spec 007).
 */
export function generateCppHeader(reel: VideoReel): string {
  const profile = DisplayProfileFactory.getDefaultProfile()
  const res = ExporterFactory.export('cpp-header', reel.frames, profile, {
    variableName: reel.name,
    includeDrawFunction: true,
    fps: reel.targetFps,
    loop: true,
    reelName: reel.name,
    sourceFilename: reel.sourceFilename,
    algorithmName: reel.settings.ditherAlgorithm,
  }) as { data: string }
  return res.data
}

/**
 * Generates a complete, self-contained standalone Arduino sketch (.ino).
 * Delegates to ExporterFactory (Spec 007).
 */
export function generateStandaloneArduinoSketch(reel: VideoReel): string {
  const profile = DisplayProfileFactory.getDefaultProfile()
  const res = ExporterFactory.export('arduino-sketch', reel.frames, profile, {
    variableName: reel.name,
    includeDrawFunction: true,
    fps: reel.targetFps,
    loop: true,
    reelName: reel.name,
    sourceFilename: reel.sourceFilename,
    algorithmName: reel.settings.ditherAlgorithm,
  }) as { data: string }
  return res.data
}

/**
 * Concatenates all frames into a single continuous raw binary Uint8Array (.bin).
 * Delegates to ExporterFactory (Spec 007).
 */
export function generateRawBinaryReel(reel: VideoReel): Uint8Array {
  const profile = DisplayProfileFactory.getDefaultProfile()
  const res = ExporterFactory.export('raw-binary', reel.frames, profile, {
    variableName: reel.name,
    includeDrawFunction: false,
    fps: reel.targetFps,
    loop: true,
    reelName: reel.name,
    sourceFilename: reel.sourceFilename,
  }) as { data: Uint8Array }
  return res.data
}

/**
 * Generates an animated monochrome GIF89a file.
 * Delegates to ExporterFactory (Spec 007).
 */
export function generateAnimatedGif(reel: VideoReel): Uint8Array {
  const profile = DisplayProfileFactory.getDefaultProfile()
  const res = ExporterFactory.export('animated-gif', reel.frames, profile, {
    variableName: reel.name,
    includeDrawFunction: false,
    fps: reel.targetFps,
    loop: true,
    reelName: reel.name,
  }) as { data: Uint8Array }
  return res.data
}

/**
 * Exports the active reel as an animated GIF download.
 */
export function exportReelAsGif(reel: VideoReel): void {
  const gifData = generateAnimatedGif(reel)
  const blob = new Blob([gifData as unknown as BlobPart], { type: 'image/gif' })
  const filename = `${reel.name || 'pixelforge_reel'}.gif`
  downloadBlob(blob, filename)
}

/**
 * Triggers a browser download of text/code content.
 */
export function downloadText(content: string, filename: string, mimeType = 'text/plain'): void {
  const blob = new Blob([content], { type: mimeType })
  downloadBlob(blob, filename)
}

/**
 * Triggers a browser download of a binary Blob.
 */
export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
