/**
 * PixelForge — C++ Header Exporter Strategy
 * Spec 007 — Scalable Architecture & Exporter Strategy Pattern
 *
 * Generates .h files with PROGMEM byte arrays for U8g2 / direct C/C++ firmware.
 */

import type { DisplayProfile } from '../../core/display/DisplayProfile';
import type { IExportStrategy, ExportOptions, ExportResult } from './ExportStrategy';

export class CppHeaderExporter implements IExportStrategy {
  readonly id = 'cpp-header';
  readonly name = 'C/C++ PROGMEM Header (.h)';
  readonly fileExtension = '.h';
  readonly description = 'C/C++ header with PROGMEM frame arrays for embedding in firmware projects.';

  exportFrames(
    frames: Uint8Array[],
    profile: DisplayProfile,
    options: ExportOptions
  ): ExportResult {
    const frameCount = frames.length;
    const fps = Math.max(1, options.fps || 15);
    const width = profile.width;
    const height = profile.height;
    const frameSize = profile.frameBytes;
    const bytesPerRow = Math.ceil(width / 8);
    const varPrefix = (options.variableName || 'animation')
      .trim()
      .replace(/[^a-zA-Z0-9_]/g, '_')
      .replace(/^[0-9]/, '_');

    let code = `// ============================================================================\n`;
    code += `// Generated by PixelForge Video & Animation Converter\n`;
    code += `// Display: ${profile.name} (${width}x${height})\n`;
    code += `// Total Frames: ${frameCount} | Target FPS: ${fps}\n`;
    code += `// Total Size: ${frameCount * frameSize} bytes (${frameSize} bytes/frame)\n`;
    code += `// ============================================================================\n\n`;
    code += `#pragma once\n`;
    code += `#include <Arduino.h>\n\n`;
    code += `#define ${varPrefix.toUpperCase()}_FRAME_COUNT ${frameCount}\n`;
    code += `#define ${varPrefix.toUpperCase()}_WIDTH ${width}\n`;
    code += `#define ${varPrefix.toUpperCase()}_HEIGHT ${height}\n`;
    code += `#define ${varPrefix.toUpperCase()}_FRAME_SIZE ${frameSize}\n`;
    code += `#define ${varPrefix.toUpperCase()}_FPS ${fps}\n\n`;
    code += `// Monochrome bit-packed bitmaps (MSB first)\n`;
    code += `const uint8_t PROGMEM ${varPrefix}_frames[${frameCount}][${frameSize}] = {\n`;

    for (let f = 0; f < frameCount; f++) {
      const frame = frames[f];
      code += `  { // Frame ${f}\n`;
      for (let row = 0; row < height; row++) {
        code += `    `;
        const rowOffset = row * bytesPerRow;
        for (let b = 0; b < bytesPerRow; b++) {
          const byteVal = frame[rowOffset + b] ?? 0;
          code += `0x${byteVal.toString(16).padStart(2, '0').toUpperCase()}, `;
        }
        code += `\n`;
      }
      code += f === frameCount - 1 ? `  }\n` : `  },\n`;
    }

    code += `};\n`;

    return {
      filename: `${varPrefix}.h`,
      mimeType: 'text/x-chdr',
      data: code,
    };
  }
}
